@echo ..........:::: Caminho do repositorio ::::..........
SET ROOT=\\10.0.0.20\Internos\NugetServer\App_Data\Packages

@echo ..........:::: Criando o pacote nupkg ::::..........
nuget pack Integrador.Pix.Santander.csproj

@echo ..........:::: Copiando o arquivo para o servidor nuget ::::..........
COPY *.nupkg, %ROOT%

@echo ..........:::: Deletando o arquivo nupkg da pasta que foi gerado ::::..........
DEL *.nupkg

@echo ..........:::: Deletando o de cache do servidor para que a DLL seja atualizada automaticamente ::::..........
DEL %ROOT%\nuget-file.cache.bin